"""
Fiat and crypto currencies data.

Fiat currency names from:
    https://en.wikipedia.org/wiki/ISO_4217
    https://github.com/blossomfinance/iso-4217-currencies/blob/master/data/iso-4217.json
Crypto currency names and decimal degits from:
    https://www.coinbase.com
    https://github.com/crypti/cryptocurrencies/blob/master/cryptocurrencies.json
Flag emojis from:
    https://emojipedia.org/search/?q=Turkmenistan
    https://github.com/opencollective/country-currency-emoji-flags/blob/main/currency-data.json
Symbols from:
    https://github.com/arshadkazmi42/currency-symbols/blob/master/currency_symbols/constants.py
"""

FIAT_CURRENCIES = {
    "AED": {
        "name": "United Arab Emirates Dirham",
        "symbol": "د.إ",
        "flag": "🇦🇪",
        "decimal_degits": 2,
    },
    "AFN": {"name": "Afghan Afghani", "symbol": "؋", "flag": "🇦🇫", "decimal_degits": 0},
    "ALL": {"name": "Albanian Lek", "symbol": "L", "flag": "🇦🇱", "decimal_degits": 0},
    "AMD": {"name": "Armenian Dram", "symbol": "֏", "flag": "🇦🇲", "decimal_degits": 0},
    "ANG": {
        "name": "Netherlands Antillean guilder",
        "symbol": "ƒ",
        "flag": "🇳🇱",
        "decimal_degits": 2,
    },
    "AOA": {
        "name": "Angolan kwanza",
        "symbol": "Kz",
        "flag": "🇦🇴",
        "decimal_degits": 0,
    },
    "ARS": {"name": "Argentine Peso", "symbol": "$", "flag": "🇦🇷", "decimal_degits": 2},
    "AUD": {
        "name": "Australian Dollar",
        "symbol": "$",
        "flag": "🇦🇺",
        "decimal_degits": 2,
    },
    "AWG": {"name": "Aruban florin", "symbol": "ƒ", "flag": "🇦🇼", "decimal_degits": 0},
    "AZN": {
        "name": "Azerbaijani Manat",
        "symbol": "₼",
        "flag": "🇦🇿",
        "decimal_degits": 2,
    },
    "BAM": {
        "name": "Bosnia-Herzegovina Convertible Mark",
        "symbol": "KM",
        "flag": "🇧🇦",
        "decimal_degits": 2,
    },
    "BBD": {
        "name": "Barbadian Dollar",
        "symbol": "$",
        "flag": "🇧🇧",
        "decimal_degits": 2,
    },
    "BDT": {
        "name": "Bangladeshi Taka",
        "symbol": "৳",
        "flag": "🇧🇩",
        "decimal_degits": 2,
    },
    "BGN": {"name": "Bulgarian Lev", "symbol": "лв", "flag": "🇧🇬", "decimal_degits": 2},
    "BHD": {
        "name": "Bahraini Dinar",
        "symbol": ".د.ب",
        "flag": "🇧🇭",
        "decimal_degits": 3,
    },
    "BIF": {
        "name": "Burundian Franc",
        "symbol": "FBu",
        "flag": "🇧🇮",
        "decimal_degits": 0,
    },
    "BMD": {
        "name": "Bermudian Dollars",
        "symbol": "$",
        "flag": "🇧🇲",
        "decimal_degits": 2,
    },
    "BND": {"name": "Brunei Dollar", "symbol": "$", "flag": "🇧🇳", "decimal_degits": 2},
    "BOB": {
        "name": "Bolivian Boliviano",
        "symbol": "$b",
        "flag": "🇧🇴",
        "decimal_degits": 2,
    },
    "BRL": {
        "name": "Brazilian Real",
        "symbol": "R$",
        "flag": "🇧🇷",
        "decimal_degits": 2,
    },
    "BSD": {
        "name": "Bahamian Dollar",
        "symbol": "$",
        "flag": "🇧🇸",
        "decimal_degits": 2,
    },
    "BTN": {
        "name": "Bhutanese ngultrum",
        "symbol": "Nu.",
        "flag": "🇧🇹",
        "decimal_degits": 0,
    },
    "BWP": {"name": "Botswanan Pula", "symbol": "P", "flag": "🇧🇼", "decimal_degits": 2},
    "BYN": {
        "name": "Belarusian ruble",
        "symbol": "Br",
        "flag": "🇧🇾",
        "decimal_degits": 2,
    },
    "BYR": {
        "name": "Belarusian Ruble",
        "symbol": "Br",
        "flag": "🇧🇾",
        "decimal_degits": 2,
    },
    "BZD": {
        "name": "Belize Dollar",
        "symbol": "BZ$",
        "flag": "🇧🇿",
        "decimal_degits": 2,
    },
    "CAD": {
        "name": "Canadian Dollar",
        "symbol": "$",
        "flag": "🇨🇦",
        "decimal_degits": 2,
    },
    "CDF": {
        "name": "Congolese Franc",
        "symbol": "FC",
        "flag": "🇨🇩",
        "decimal_degits": 2,
    },
    "CHF": {"name": "Swiss Franc", "symbol": "CHF", "flag": "🇨🇭", "decimal_degits": 2},
    "CLF": {
        "name": "Unidad de Fomento",
        "symbol": "UF",
        "flag": "🇨🇱",
        "decimal_degits": 2,
    },
    "CLP": {"name": "Chilean Peso", "symbol": "$", "flag": "🇨🇱", "decimal_degits": 0},
    "CNY": {"name": "Chinese Yuan", "symbol": "¥", "flag": "🇨🇳", "decimal_degits": 2},
    "COP": {"name": "Colombian Peso", "symbol": "$", "flag": "🇨🇴", "decimal_degits": 0},
    "CRC": {
        "name": "Costa Rican Colón",
        "symbol": "₡",
        "flag": "🇨🇷",
        "decimal_degits": 0,
    },
    "CUC": {
        "name": "Cuban convertible peso",
        "symbol": "$",
        "flag": "🇨🇺",
        "decimal_degits": 0,
    },
    "CVE": {
        "name": "Cape Verdean Escudo",
        "symbol": "$",
        "flag": "🇨🇻",
        "decimal_degits": 2,
    },
    "CZK": {
        "name": "Czech Republic Koruna",
        "symbol": "Kč",
        "flag": "🇨🇿",
        "decimal_degits": 2,
    },
    "DJF": {
        "name": "Djiboutian Franc",
        "symbol": "Fdj",
        "flag": "🇩🇯",
        "decimal_degits": 0,
    },
    "DKK": {"name": "Danish Krone", "symbol": "kr", "flag": "🇩🇰", "decimal_degits": 2},
    "DOP": {
        "name": "Dominican Peso",
        "symbol": "RD$",
        "flag": "🇩🇴",
        "decimal_degits": 2,
    },
    "DZD": {
        "name": "Algerian Dinar",
        "symbol": "دج",
        "flag": "🇩🇿",
        "decimal_degits": 2,
    },
    "EGP": {"name": "Egyptian Pound", "symbol": "£", "flag": "🇪🇬", "decimal_degits": 2},
    "ETB": {
        "name": "Ethiopian Birr",
        "symbol": "Br",
        "flag": "🇪🇹",
        "decimal_degits": 2,
    },
    "EUR": {"name": "Euro", "symbol": "€", "flag": "🇪🇺", "decimal_degits": 2},
    "FJD": {"name": "Fiji dollar", "symbol": "$", "flag": "🇫🇯", "decimal_degits": 0},
    "FKP": {
        "name": "Falkland Islands Pound",
        "symbol": "£",
        "flag": "🇫🇰",
        "decimal_degits": 2,
    },
    "GBP": {
        "name": "British Pound Sterling",
        "symbol": "£",
        "flag": "🇬🇧",
        "decimal_degits": 2,
    },
    "GEL": {"name": "Georgian Lari", "symbol": "₾", "flag": "🇬🇪", "decimal_degits": 2},
    "GHS": {
        "name": "Ghanaian Cedi",
        "symbol": "GH₵",
        "flag": "🇬🇭",
        "decimal_degits": 2,
    },
    "GIP": {
        "name": "Gibraltar pound",
        "symbol": "£",
        "flag": "🇬🇮",
        "decimal_degits": 0,
    },
    "GMD": {"name": "Gambian dalasi", "symbol": "D", "flag": "🇬🇲", "decimal_degits": 0},
    "GNF": {"name": "Guinean Franc", "symbol": "FG", "flag": "🇬🇳", "decimal_degits": 0},
    "GTQ": {
        "name": "Guatemalan Quetzal",
        "symbol": "Q",
        "flag": "🇬🇹",
        "decimal_degits": 2,
    },
    "GYD": {
        "name": "Guyanese Dollar",
        "symbol": "$",
        "flag": "🇬🇾",
        "decimal_degits": 2,
    },
    "HKD": {
        "name": "Hong Kong Dollar",
        "symbol": "$",
        "flag": "🇭🇰",
        "decimal_degits": 2,
    },
    "HNL": {
        "name": "Honduran Lempira",
        "symbol": "L",
        "flag": "🇭🇳",
        "decimal_degits": 2,
    },
    "HRK": {"name": "Croatian Kuna", "symbol": "kn", "flag": "🇭🇷", "decimal_degits": 2},
    "HTG": {"name": "Haitian gourde", "symbol": "G", "flag": "🇭🇹", "decimal_degits": 0},
    "HUF": {
        "name": "Hungarian Forint",
        "symbol": "Ft",
        "flag": "🇭🇺",
        "decimal_degits": 0,
    },
    "IDR": {
        "name": "Indonesian Rupiah",
        "symbol": "Rp",
        "flag": "🇮🇩",
        "decimal_degits": 0,
    },
    "ILS": {
        "name": "Israeli New Sheqel",
        "symbol": "₪",
        "flag": "🇮🇱",
        "decimal_degits": 2,
    },
    "INR": {"name": "Indian Rupee", "symbol": "₹", "flag": "🇮🇳", "decimal_degits": 2},
    "IQD": {"name": "Iraqi Dinar", "symbol": "ع.د", "flag": "🇮🇶", "decimal_degits": 0},
    "ISK": {
        "name": "Icelandic Króna",
        "symbol": "kr",
        "flag": "🇮🇸",
        "decimal_degits": 0,
    },
    "JMD": {
        "name": "Jamaican Dollar",
        "symbol": "J$",
        "flag": "🇯🇲",
        "decimal_degits": 2,
    },
    "JOD": {
        "name": "Jordanian Dinar",
        "symbol": "JD",
        "flag": "🇯🇴",
        "decimal_degits": 3,
    },
    "JPY": {"name": "Japanese Yen", "symbol": "¥", "flag": "🇯🇵", "decimal_degits": 0},
    "KES": {
        "name": "Kenyan Shilling",
        "symbol": "KSh",
        "flag": "🇰🇪",
        "decimal_degits": 2,
    },
    "KGS": {
        "name": "Kyrgyzstani som",
        "symbol": "лв",
        "flag": "🇰🇬",
        "decimal_degits": 0,
    },
    "KHR": {"name": "Cambodian Riel", "symbol": "៛", "flag": "🇰🇭", "decimal_degits": 2},
    "KMF": {
        "name": "Comorian Franc",
        "symbol": "CF",
        "flag": "🇰🇲",
        "decimal_degits": 0,
    },
    "KRW": {
        "name": "South Korean Won",
        "symbol": "₩",
        "flag": "🇰🇷",
        "decimal_degits": 0,
    },
    "KWD": {"name": "Kuwaiti Dinar", "symbol": "KD", "flag": "🇰🇼", "decimal_degits": 3},
    "KYD": {
        "name": "Cayman Islands dollar",
        "symbol": "$",
        "flag": "🇰🇾",
        "decimal_degits": 0,
    },
    "KZT": {
        "name": "Kazakhstani Tenge",
        "symbol": "лв",
        "flag": "🇰🇿",
        "decimal_degits": 2,
    },
    "LAK": {"name": "Lao kip", "symbol": "₭", "flag": "🇱🇦", "decimal_degits": 12},
    "LBP": {"name": "Lebanese Pound", "symbol": "£", "flag": "🇱🇧", "decimal_degits": 0},
    "LKR": {
        "name": "Sri Lankan Rupee",
        "symbol": "₨",
        "flag": "🇱🇰",
        "decimal_degits": 2,
    },
    "LRD": {
        "name": "Liberian dollar",
        "symbol": "$",
        "flag": "🇱🇷",
        "decimal_degits": 0,
    },
    "LSL": {"name": "Lesotho loti", "symbol": "M", "flag": "🇱🇸", "decimal_degits": 0},
    "LYD": {"name": "Libyan Dinar", "symbol": "LD", "flag": "🇱🇾", "decimal_degits": 3},
    "MAD": {
        "name": "Moroccan Dirham",
        "symbol": "MAD",
        "flag": "🇲🇦",
        "decimal_degits": 2,
    },
    "MDL": {"name": "Moldovan Leu", "symbol": "lei", "flag": "🇲🇩", "decimal_degits": 2},
    "MGA": {
        "name": "Malagasy Ariary",
        "symbol": "Ar",
        "flag": "🇲🇬",
        "decimal_degits": 0,
    },
    "MKD": {
        "name": "Macedonian Denar",
        "symbol": "ден",
        "flag": "🇲🇰",
        "decimal_degits": 2,
    },
    "MMK": {"name": "Myanma Kyat", "symbol": "K", "flag": "🇲🇲", "decimal_degits": 0},
    "MNT": {
        "name": "Mongolian Tughrik",
        "symbol": "₮",
        "flag": "🇲🇳",
        "decimal_degits": 2,
    },
    "MOP": {
        "name": "Macanese Pataca",
        "symbol": "MOP$",
        "flag": "🇲🇴",
        "decimal_degits": 2,
    },
    "MRO": {
        "name": "Mauritanian ouguiya",
        "symbol": "UM",
        "flag": "🇲🇷",
        "decimal_degits": 0,
    },
    "MUR": {
        "name": "Mauritian Rupee",
        "symbol": "₨",
        "flag": "🇲🇺",
        "decimal_degits": 0,
    },
    "MVR": {
        "name": "Maldivian rufiyaa",
        "symbol": "Rf",
        "flag": "🇲🇻",
        "decimal_degits": 0,
    },
    "MWK": {
        "name": "Malawian kwacha",
        "symbol": "MK",
        "flag": "🇲🇼",
        "decimal_degits": 0,
    },
    "MXN": {"name": "Mexican Peso", "symbol": "$", "flag": "🇲🇽", "decimal_degits": 2},
    "MYR": {
        "name": "Malaysian Ringgit",
        "symbol": "RM",
        "flag": "🇲🇾",
        "decimal_degits": 2,
    },
    "MZN": {
        "name": "Mozambican Metical",
        "symbol": "MT",
        "flag": "🇲🇿",
        "decimal_degits": 2,
    },
    "NAD": {
        "name": "Namibian Dollar",
        "symbol": "$",
        "flag": "🇳🇦",
        "decimal_degits": 2,
    },
    "NGN": {"name": "Nigerian Naira", "symbol": "₦", "flag": "🇳🇬", "decimal_degits": 2},
    "NIO": {
        "name": "Nicaraguan Córdoba",
        "symbol": "C$",
        "flag": "🇳🇮",
        "decimal_degits": 2,
    },
    "NOK": {
        "name": "Norwegian Krone",
        "symbol": "kr",
        "flag": "🇳🇴",
        "decimal_degits": 2,
    },
    "NPR": {"name": "Nepalese Rupee", "symbol": "₨", "flag": "🇳🇵", "decimal_degits": 2},
    "NZD": {
        "name": "New Zealand Dollar",
        "symbol": "$",
        "flag": "🇳🇿",
        "decimal_degits": 2,
    },
    "OMR": {"name": "Omani Rial", "symbol": "﷼", "flag": "🇴🇲", "decimal_degits": 3},
    "PAB": {
        "name": "Panamanian Balboa",
        "symbol": "B/.",
        "flag": "🇵🇦",
        "decimal_degits": 2,
    },
    "PEN": {
        "name": "Peruvian Nuevo Sol",
        "symbol": "S/.",
        "flag": "🇵🇪",
        "decimal_degits": 2,
    },
    "PGK": {
        "name": "Papua New Guinean kina",
        "symbol": "K",
        "flag": "🇵🇬",
        "decimal_degits": 0,
    },
    "PHP": {
        "name": "Philippine Peso",
        "symbol": "₱",
        "flag": "🇵🇭",
        "decimal_degits": 2,
    },
    "PKR": {
        "name": "Pakistani Rupee",
        "symbol": "₨",
        "flag": "🇵🇰",
        "decimal_degits": 0,
    },
    "PLN": {"name": "Polish Zloty", "symbol": "zł", "flag": "🇵🇱", "decimal_degits": 2},
    "PYG": {
        "name": "Paraguayan Guarani",
        "symbol": "Gs",
        "flag": "🇵🇾",
        "decimal_degits": 0,
    },
    "QAR": {"name": "Qatari Rial", "symbol": "﷼", "flag": "🇶🇦", "decimal_degits": 2},
    "RON": {"name": "Romanian Leu", "symbol": "lei", "flag": "🇷🇴", "decimal_degits": 2},
    "RSD": {
        "name": "Serbian Dinar",
        "symbol": "Дин.",
        "flag": "🇷🇸",
        "decimal_degits": 0,
    },
    "RUB": {"name": "Russian Ruble", "symbol": "₽", "flag": "🇷🇺", "decimal_degits": 2},
    "RWF": {"name": "Rwandan Franc", "symbol": "R₣", "flag": "🇷🇼", "decimal_degits": 0},
    "SAR": {"name": "Saudi Riyal", "symbol": "﷼", "flag": "🇸🇦", "decimal_degits": 2},
    "SBD": {
        "name": "Solomon Islands dollar",
        "symbol": "$",
        "flag": "🇸🇧",
        "decimal_degits": 0,
    },
    "SCR": {
        "name": "Seychelles rupee",
        "symbol": "₨",
        "flag": "🇸🇨",
        "decimal_degits": 0,
    },
    "SEK": {"name": "Swedish Krona", "symbol": "kr", "flag": "🇸🇪", "decimal_degits": 2},
    "SHP": {
        "name": "Saint Helena pound",
        "symbol": "£",
        "flag": "🇸🇭",
        "decimal_degits": 0,
    },
    "SKK": {"name": "Slovak koruna", "symbol": "", "flag": "🇸🇰", "decimal_degits": 2},
    "SLL": {
        "name": "Sierra Leonean leone",
        "symbol": "Le",
        "flag": "🇸🇱",
        "decimal_degits": 0,
    },
    "SOS": {
        "name": "Somali Shilling",
        "symbol": "S",
        "flag": "🇸🇴",
        "decimal_degits": 0,
    },
    "SRD": {
        "name": "Surinami guilder",
        "symbol": "$",
        "flag": "🇸🇷",
        "decimal_degits": 2,
    },
    "SSP": {
        "name": "South Sudanese Pound",
        "symbol": "£",
        "flag": "🇸🇸",
        "decimal_degits": 2,
    },
    "STD": {
        "name": "São Tomé and Príncipe dobra",
        "symbol": "Db",
        "flag": "🇸🇹",
        "decimal_degits": 2,
    },
    "SVC": {
        "name": "Salvadoran colón",
        "symbol": "$",
        "flag": "🇸🇻",
        "decimal_degits": 0,
    },
    "SZL": {
        "name": "Swazi lilangeni",
        "symbol": "E",
        "flag": "🇸🇿",
        "decimal_degits": 0,
    },
    "THB": {"name": "Thai Baht", "symbol": "฿", "flag": "🇹🇭", "decimal_degits": 2},
    "TJS": {
        "name": "Tajikistani somoni",
        "symbol": "SM",
        "flag": "🇹🇯",
        "decimal_degits": 0,
    },
    "TMT": {
        "name": "Turkmenistan manat",
        "symbol": "T",
        "flag": "🇹🇲",
        "decimal_degits": 0,
    },
    "TND": {
        "name": "Tunisian Dinar",
        "symbol": "د.ت",
        "flag": "🇹🇳",
        "decimal_degits": 3,
    },
    "TOP": {
        "name": "Tongan Paʻanga",
        "symbol": "T$",
        "flag": "🇹🇴",
        "decimal_degits": 2,
    },
    "TRY": {"name": "Turkish Lira", "symbol": "₺", "flag": "🇹🇷", "decimal_degits": 2},
    "TTD": {
        "name": "Trinidad and Tobago Dollar",
        "symbol": "TT$",
        "flag": "🇹🇹",
        "decimal_degits": 2,
    },
    "TWD": {
        "name": "New Taiwan Dollar",
        "symbol": "NT$",
        "flag": "🇹🇼",
        "decimal_degits": 2,
    },
    "TZS": {
        "name": "Tanzanian Shilling",
        "symbol": "TSh",
        "flag": "🇹🇿",
        "decimal_degits": 0,
    },
    "UAH": {
        "name": "Ukrainian Hryvnia",
        "symbol": "₴",
        "flag": "🇺🇦",
        "decimal_degits": 2,
    },
    "UGX": {
        "name": "Ugandan Shilling",
        "symbol": "USh",
        "flag": "🇺🇬",
        "decimal_degits": 0,
    },
    "UYU": {
        "name": "Uruguayan Peso",
        "symbol": "$U",
        "flag": "🇺🇾",
        "decimal_degits": 2,
    },
    "UZS": {
        "name": "Uzbekistan Som",
        "symbol": "лв",
        "flag": "🇺🇿",
        "decimal_degits": 0,
    },
    "VES": {
        "name": "Venezuelan bolívar soberano",
        "symbol": "",
        "flag": "🇻🇪",
        "decimal_degits": 2,
    },
    "VND": {
        "name": "Vietnamese Dong",
        "symbol": "₫",
        "flag": "🇻🇳",
        "decimal_degits": 0,
    },
    "VUV": {"name": "Vanuatu vatu", "symbol": "VT", "flag": "🇻🇺", "decimal_degits": 0},
    "WST": {"name": "Samoan tala", "symbol": "WS$", "flag": "🇼🇸", "decimal_degits": 0},
    "XAF": {
        "name": "CFA Franc BEAC",
        "symbol": "FCFA",
        "flag": "🇨🇲",
        "decimal_degits": 0,
    },
    "XAG": {
        "name": "Silver (one troy ounce)",
        "symbol": "",
        "flag": "",
        "decimal_degits": 0,
    },
    "XAU": {
        "name": "Gold (one troy ounce)",
        "symbol": "",
        "flag": "",
        "decimal_degits": 0,
    },
    "XCD": {
        "name": "Eastern Carribean dollar",
        "symbol": "$",
        "flag": "🇦🇮",
        "decimal_degits": 0,
    },
    "XDR": {
        "name": "Special drawing rights",
        "symbol": "",
        "flag": "",
        "decimal_degits": 0,
    },
    "XOF": {
        "name": "CFA Franc BCEAO",
        "symbol": "CFA",
        "flag": "🇧🇯",
        "decimal_degits": 0,
    },
    "XPD": {
        "name": "Palladium (one troy ounce)",
        "symbol": "",
        "flag": "",
        "decimal_degits": 0,
    },
    "XPF": {
        "name": "CFP franc (franc Pacifique)",
        "symbol": "₣",
        "flag": "🇵🇫",
        "decimal_degits": 0,
    },
    "XPT": {
        "name": "Platinum (one troy ounce)",
        "symbol": "",
        "flag": "",
        "decimal_degits": 0,
    },
    "YER": {"name": "Yemeni Rial", "symbol": "﷼", "flag": "🇾🇪", "decimal_degits": 0},
    "ZAR": {
        "name": "South African Rand",
        "symbol": "R",
        "flag": "🇿🇦",
        "decimal_degits": 2,
    },
    "ZMW": {"name": "Zambian kwacha", "symbol": "", "flag": "🇿🇲", "decimal_degits": 2},
    "JEP": {"name": "Jersey pound", "symbol": "£", "flag": "🇯🇪", "decimal_degits": 2},
    "GGP": {"name": "Guernsey pound", "symbol": "£", "flag": "🇬🇬", "decimal_degits": 2},
    "IMP": {
        "name": "Isle of Man pound",
        "symbol": "£",
        "flag": "🇮🇲",
        "decimal_degits": 2,
    },
    "GBX": {
        "name": "Penny sterling",
        "symbol": "£p",
        "flag": "🇬🇧",
        "decimal_degits": 2,
    },
    "CNH": {
        "name": "Chinese yuan (offshore)",
        "symbol": "",
        "flag": "🇭🇰",
        "decimal_degits": 2,
    },
    "TMM": {
        "name": "Turkmenistani manat",
        "symbol": "",
        "flag": "🇹🇲",
        "decimal_degits": 2,
    },
    "ZWL": {
        "name": "Zimbabwean dollar",
        "symbol": "",
        "flag": "🇿🇼",
        "decimal_degits": 0,
    },
    "SGD": {
        "name": "Singapore Dollar",
        "symbol": "$",
        "flag": "🇸🇬",
        "decimal_degits": 2,
    },
    "USD": {"name": "US Dollar", "symbol": "$", "flag": "🇺🇸", "decimal_degits": 2},
}

CRYPTO_CURRENCIES = {
    "BTC": {"name": "Bitcoin", "symbol": "฿"},
    "BCH": {"name": "Bitcoin Cash", "symbol": ""},
    "BSV": {"name": "Bitcoin SV", "symbol": ""},
    "ETH": {"name": "Ethereum", "symbol": "Ξ"},
    "ETH2": {"name": "Ethereum 2", "symbol": ""},
    "ETC": {"name": "Ethereum Classic", "symbol": ""},
    "LTC": {"name": "Litecoin", "symbol": "Ł"},
    "ZRX": {"name": "0x", "symbol": ""},
    "USDC": {"name": "USD Coin", "symbol": ""},
    "BAT": {"name": "Basic Attention Token", "symbol": ""},
    "MANA": {"name": "Decentraland", "symbol": ""},
    "KNC": {"name": "Kyber Network", "symbol": ""},
    "LINK": {"name": "ChainLink", "symbol": ""},
    "DNT": {"name": "district0x", "symbol": ""},
    "MKR": {"name": "Maker", "symbol": ""},
    "CVC": {"name": "Civic", "symbol": ""},
    "OMG": {"name": "OmiseGo", "symbol": ""},
    "DAI": {"name": "Dai", "symbol": ""},
    "ZEC": {"name": "ZCash", "symbol": ""},
    "XRP": {"name": "XRP", "symbol": ""},
    "REP": {"name": "Augur", "symbol": ""},
    "XLM": {"name": "Stellar", "symbol": ""},
    "EOS": {"name": "EOS", "symbol": ""},
    "XTZ": {"name": "Tezos", "symbol": ""},
    "ALGO": {"name": "Algorand", "symbol": ""},
    "DASH": {"name": "Dash", "symbol": ""},
    "ATOM": {"name": "Atomic Coin", "symbol": ""},
    "OXT": {"name": "Orchid", "symbol": ""},
    "COMP": {"name": "Compound Coin", "symbol": ""},
    "ENJ": {"name": "Enjin Coin", "symbol": ""},
    "REPV2": {"name": "REPv2", "symbol": ""},
    "BAND": {"name": "Band Protocol", "symbol": ""},
    "NMR": {"name": "Numeraire", "symbol": ""},
    "CGLD": {"name": "Celo", "symbol": ""},
    "UMA": {"name": "UMA", "symbol": ""},
    "LRC": {"name": "Loopring", "symbol": ""},
    "YFI": {"name": "yearn.finance", "symbol": ""},
    "UNI": {"name": "Universe", "symbol": ""},
    "BAL": {"name": "Balancer", "symbol": ""},
    "REN": {"name": "Republic Token", "symbol": ""},
    "WBTC": {"name": "Wrapped Bitcoin", "symbol": ""},
    "NU": {"name": "NuCypher", "symbol": ""},
    "YFII": {"name": "DFI.Money", "symbol": ""},
    "FIL": {"name": "FileCoin", "symbol": ""},
    "AAVE": {"name": "Aave", "symbol": ""},
    "BNT": {"name": "Bancor Network Token", "symbol": ""},
    "GRT": {"name": "The Graph", "symbol": ""},
    "SNX": {"name": "Synthetix", "symbol": ""},
    "STORJ": {"name": "Storj", "symbol": ""},
    "SUSHI": {"name": "SushiSwap", "symbol": ""},
    "MATIC": {"name": "Polygon", "symbol": ""},
    "SKL": {"name": "SKALE", "symbol": ""},
    "ADA": {"name": "Cardano", "symbol": ""},
    "ANKR": {"name": "Ankr Network", "symbol": ""},
    "CRV": {"name": "Cravy", "symbol": ""},
    "ICP": {"name": "Internet Computer", "symbol": ""},
    "NKN": {"name": "NKN", "symbol": ""},
    "OGN": {"name": "Origin Token", "symbol": ""},
    "1INCH": {"name": "1inch", "symbol": ""},
    "USDT": {"name": "Tether", "symbol": ""},
    "FORTH": {"name": "Ampleforth Governance", "symbol": ""},
    "CTSI": {"name": "Cartesi", "symbol": ""},
    "TRB": {"name": "Tellor", "symbol": ""},
    "POLY": {"name": "PolyBit", "symbol": ""},
    "MIR": {"name": "Mirror Protocol", "symbol": ""},
    "RLC": {"name": "iEx.ec", "symbol": ""},
    "DOT": {"name": "Dotcoin", "symbol": ""},
    "SOL": {"name": "Sola", "symbol": ""},
    "DOGE": {"name": "Dogecoin", "symbol": ""},
    "MLN": {"name": "Melon", "symbol": ""},
    "GTC": {"name": "Game", "symbol": ""},
    "AMP": {"name": "Synereo", "symbol": ""},
    "SHIB": {"name": "SHIBA INU", "symbol": ""},
    "CHZ": {"name": "Chiliz", "symbol": ""},
    "KEEP": {"name": "Keep Network", "symbol": ""},
    "LPT": {"name": "Livepeer", "symbol": ""},
    "QNT": {"name": "Quant", "symbol": ""},
    "BOND": {"name": "BarnBridge", "symbol": ""},
    "RLY": {"name": "Rally", "symbol": ""},
    "CLV": {"name": "CleverCoin", "symbol": ""},
    "FARM": {"name": "FARM Coin", "symbol": ""},
    "MASK": {"name": "Mask Network", "symbol": ""},
    "FET": {"name": "Fetch.AI", "symbol": ""},
    "PAX": {"name": "Paxos Standard", "symbol": ""},
    "ACH": {"name": "AchieveCoin", "symbol": ""},
    "ASM": {"name": "Assemble Protocol", "symbol": ""},
    "PLA": {"name": "PlayChip", "symbol": ""},
    "RAI": {"name": "Rai Reflex Index", "symbol": ""},
    "TRIBE": {"name": "TribeToken", "symbol": ""},
    "ORN": {"name": "Orion Protocol", "symbol": ""},
    "IOTX": {"name": "IoTeX Network", "symbol": ""},
    "UST": {"name": "TerraUSD", "symbol": ""},
    "QUICK": {"name": "QuickSwap", "symbol": ""},
    "AXS": {"name": "AXS", "symbol": ""},
    "REQ": {"name": "Request Network", "symbol": ""},
    "WLUNA": {"name": "Wrapped LUNA Token", "symbol": ""},
    "TRU": {"name": "TrueFi", "symbol": ""},
    "RAD": {"name": "Radicle", "symbol": ""},
    "COTI": {"name": "COTI", "symbol": ""},
    "DDX": {"name": "DerivaDAO", "symbol": ""},
    "SUKU": {"name": "SUKU", "symbol": ""},
    "RGT": {"name": "Retail.Global", "symbol": ""},
    "XYO": {"name": "XY Oracle", "symbol": ""},
    "ZEN": {"name": "ZEN", "symbol": ""},
    "AUCTION": {"name": "Bounce Token", "symbol": ""},
    "JASMY": {"name": "JASMY", "symbol": ""},
    "WCFG": {"name": "Wrapped Centrifuge", "symbol": ""},
    "BTRST": {"name": "Braintrust", "symbol": ""},
    "AGLD": {"name": "Adventure Gold", "symbol": ""},
    "AVAX": {"name": "Avalanche", "symbol": ""},
    "FX": {"name": "FCoin", "symbol": ""},
    "TRAC": {"name": "OriginTrail", "symbol": ""},
    "LCX": {"name": "LCX", "symbol": ""},
    "ARPA": {"name": "ArpaCoin", "symbol": ""},
    "BADGER": {"name": "Badger DAO", "symbol": ""},
    "KRL": {"name": "Kryll", "symbol": ""},
    "PERP": {"name": "Perpetual Protocol", "symbol": ""},
    "RARI": {"name": "Rarible", "symbol": ""},
    "DESO": {"name": "Decentralized Social", "symbol": ""},
    "API3": {"name": "API3", "symbol": ""},
    "NCT": {"name": "PolySwarm", "symbol": ""},
    "SHPING": {"name": "Shping Coin", "symbol": ""},
    "CRO": {"name": "Crypto.com Chain Token", "symbol": ""},
    "MDT": {"name": "Midnight", "symbol": ""},
    "VGX": {"name": "Voyager Token", "symbol": ""},
    "ALCX": {"name": "Alchemix", "symbol": ""},
    "COVAL": {"name": "Circuits of Value", "symbol": ""},
    "FOX": {"name": "Shapeshift FOX Token", "symbol": ""},
    "MUSD": {"name": "MUSDcoin", "symbol": ""},
    "GALA": {"name": "Gala", "symbol": ""},
    "POWR": {"name": "Power Ledger", "symbol": ""},
    "GYEN": {"name": "GYEN", "symbol": ""},
    "INV": {"name": "Invictus", "symbol": ""},
    "LQTY": {"name": "Liquity", "symbol": ""},
    "PRO": {"name": "Propy", "symbol": ""},
    "SPELL": {"name": "Spell Token", "symbol": ""},
    "ENS": {"name": "Ethereum Name Service", "symbol": ""},
    "BLZ": {"name": "Bluzelle", "symbol": ""},
    "IDEX": {"name": "IDEX", "symbol": ""},
    "MCO2": {"name": "Moss Carbon Credit", "symbol": ""},
    "POLS": {"name": "Polkastarter", "symbol": ""},
    "SUPER": {"name": "SuperCoin", "symbol": ""},
    "STX": {"name": "Stox", "symbol": ""},
    "GODS": {"name": "Gods Unchained", "symbol": ""},
    "IMX": {"name": "Impact", "symbol": ""},
    "RBN": {"name": "Ribbon Finance", "symbol": ""},
    "BICO": {"name": "BICONOMY (BICO)", "symbol": ""},
    "GFI": {"name": "Goldfinch Protocol", "symbol": ""},
    "XMR": {"name":"Monero","symbol":"Ɱ"},
}
